### ISSUE TITLE
Support for "duration"

### ISSUE THREAD

**Issue by pahen** [emilohman/homey-plejd#3]
Hi,

Is it possible to add support for "duration" as IKEA devices supports? Or is it a Zigbee specific feature maybe?

See https://github.com/athombv/com.ikea.tradfri/blob/72f14571df095a7365c903be1c5d171edb642e75/drivers/rgb_bulb/driver.compose.json#L17

![IMG_3333](https://user-images.githubusercontent.com/353888/107113256-14cb1480-685e-11eb-9de0-5d1eaed80be4.PNG)

**Comment by emilohman** [comment]
It isn't supported by the Plejd hardware as for zigbee devices. 

The Plejd implementation for Home Assistant has a workaround for it. The problem is that the duration runs in the software (HA) so it can affect other state changes and they can't run in parallell. So if you turns 4 light on with a 2sec duration it will take 8sec not 2sec as expected.

**Comment by pahen** [comment]
Ok, too bad. I suppose it's not worth looking more into this then.
